"""migrate

Revision ID: 756afe9b4ae4
Revises: 
Create Date: 2018-03-25 16:56:18.318838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756afe9b4ae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_collection', sa.Column('collecti_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_collection_collection_id_fkey', 'user_collection', type_='foreignkey')
    op.create_foreign_key(None, 'user_collection', 'userCollections', ['collecti_id'], ['id'])
    op.drop_column('user_collection', 'collection_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_collection', sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_collection', type_='foreignkey')
    op.create_foreign_key('user_collection_collection_id_fkey', 'user_collection', 'userCollections', ['collection_id'], ['id'])
    op.drop_column('user_collection', 'collecti_id')
    # ### end Alembic commands ###
